image: node:14.8.0-stretch

stages:
  - test
  - cdn
  - deploy

test-stage:
  stage: test
  script:
    - npm install
    - npm run lint
  tags:
    - docker

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/frontend/configurations && git stash && git checkout master && git pull
    - cd /schroedinger/frontend && git stash && git checkout master && git pull
    - docker-compose  --env-file ./configurations/.env up -d --build
  only:
    - master
  tags:
    - shell
