image: node:14.8.0-stretch

stages:
  - test
  - deploy

test-stage:
  stage: test
  script:
    - npm install
    - npm run lint
  tags:
    - docker

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/frontend
    - git stash
    - git checkout master
    - git pull
    - docker-compose up -d --build
  only:
    - master
  tags:
    - shell
