image: node:14.8.0-stretch

stages:
  - test
  - build
  - cdn
  - deploy

test-stage:
  stage: test
  script:
    - npm install
    - npm run lint
    - npm run test
  coverage: /All\sfiles.*?\s+(\d+.\d+)/
  tags:
    - docker
  artifacts:
    expire_in: 1 hour
    paths:
      - node_modules

build-stage:
  stage: build
  script:
    - CI=false PUBLIC_URL=${SCHROEDINGER_CDN_PUBLIC} npm run build
  tags:
    - docker
  only:
    - master
  artifacts:
    expire_in: 1 hour
    paths:
      - build

cdn-stage:
  stage: cdn
  image: python:latest
  script:
    - pip install awscli
    - aws s3 cp build/ s3://${SCHROEDINGER_CDN_STORAGE}/ --endpoint-url https://s3-${SCHROEDINGER_CDN_REGION}.amazonaws.com --recursive --acl public-read
  tags:
    - docker
  only:
    - master

deploy-stage:
  stage: deploy
  script:
    - cd /schroedinger/frontend/configurations && git stash && git checkout master && git pull
    - cd /schroedinger/frontend && git stash && git checkout master && git pull
    - docker-compose  --env-file ./configurations/.env up -d --build
  only:
    - master
  tags:
    - shell
