version: "3.7"
services:
  schroedinger-frontend:
    build: .
    container_name: schroedinger-frontend
    restart: always
    ports:
      - 3001:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s

