version: "3.7"
services:
  schroedinger-frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - SCHROEDINGER_CDN_PUBLIC=${SCHROEDINGER_CDN_PUBLIC}
    container_name: schroedinger-frontend
    restart: always
    ports:
      - ${SCHROEDINGER_FRONTEND_PORT}:80
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 120s

  schroedinger-autoheal:
    restart: always
    container_name: schroedinger-frontend-autoheal
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_START_PERIOD=120
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

