version: "3"
services:
  schroedinger-frontend:
    build: .
    container_name: schroedinger-frontend
    restart: always
    ports:
      - 3001:80
    volumes:
      - schroedinger_frontend_node_modules:/app/node_modules
    healthcheck:
      test: ["CMD", "curl", "--silent", "--show-error", "--fail", "http://localhost:3001"]
      interval: 200s
      timeout: 200s
      retries: 5

volumes:
  schroedinger_frontend_node_modules:
