const SET_OVERALL_COUNT = "SET_OVERALL_COUNT";
const SET_PUBLIC_COUNT = "SET_PUBLIC_COUNT";
const SET_PRIVATE_COUNT = "SET_PRIVATE_COUNT";
const SET_ACTIVE_COUNT = "SET_ACTIVE_COUNT";
const SET_PENDING_COUNT = "SET_PENDING_COUNT";
const SET_CLOSED_COUNT = "SET_CLOSED_COUNT";

export {
    SET_OVERALL_COUNT,
    SET_ACTIVE_COUNT,
    SET_CLOSED_COUNT,
    SET_PENDING_COUNT,
    SET_PRIVATE_COUNT,
    SET_PUBLIC_COUNT
};
